import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — YieldWise AI",
  description: "YieldWise AI terms of service and usage agreement.",
};

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 800, margin: "0 auto", padding: "60px 24px" }}>
      <h1 style={{ fontSize: 36, fontWeight: 800, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ color: "var(--text-muted)", marginBottom: 40, fontSize: 14 }}>Last updated: April 20, 2026</p>

      {[
        { title: "1. Acceptance of Terms", content: "By accessing or using YieldWise AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services." },
        { title: "2. Description of Service", content: "YieldWise AI is an AI-powered financial analysis platform that provides portfolio tracking, stock screening, dividend analysis, and AI-generated investment insights. Our service is for informational purposes only." },
        { title: "3. Not Financial Advice", content: "IMPORTANT: YieldWise AI does NOT provide financial, investment, tax, or legal advice. All analysis, signals, and recommendations generated by our AI are for informational purposes only. You should always consult with a qualified financial advisor before making any investment decisions. We are not responsible for any financial losses resulting from actions taken based on our AI analysis." },
        { title: "4. User Accounts", content: "You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information when creating an account. We reserve the right to suspend or terminate accounts that violate these terms." },
        { title: "5. Subscription & Payments", content: "Paid subscriptions are billed monthly or annually. You may cancel at any time. Refunds are provided on a case-by-case basis. Prices are subject to change with 30 days notice." },
        { title: "6. Data Accuracy", content: "While we strive to provide accurate financial data, we cannot guarantee the accuracy, completeness, or timeliness of any information. Market data is sourced from third-party providers and may be delayed." },
        { title: "7. Intellectual Property", content: "All content, features, and functionality of YieldWise AI are owned by us and protected by international copyright, trademark, and other intellectual property laws." },
        { title: "8. Limitation of Liability", content: "YieldWise AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or other intangible losses." },
        { title: "9. Changes to Terms", content: "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms." },
        { title: "10. Contact", content: "For questions about these terms, contact us at legal@yieldwise.ai." },
      ].map(s => (
        <div key={s.title} style={{ marginBottom: 32 }}>
          <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 12 }}>{s.title}</h2>
          <p style={{ fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.8 }}>{s.content}</p>
        </div>
      ))}
    </div>
  );
}
